### ISSUE TITLE
diagonal and fresco in same layout 

### ISSUE THREAD

**Issue by adelhaddad** [florent37/DiagonalLayout#1]
if you remplace CircleImageView by SimpleDraweeView "fresco Facebook" it become hidden dont know why , you can test it .

xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:diagonal="http://schemas.android.com/apk/res-auto"
xmlns:fresco="http://schemas.android.com/tools"

**Comment by florent37** [comment]
only use 

xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto"

and replace all the fresco: and diagonal: attributes to app:
