### ISSUE TITLE
Not rendering in android studio 

### ISSUE THREAD

**Issue by sandeshlasnapure** [florent37/DiagonalLayout#10]
Layout not showing in xml editor.

**Comment by omiderfanmanesh** [comment]
endering failed with a known bug. Please try a rebuild.  The following classes could not be instantiated:
- android.support.v7.widget.AppCompatTextView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details java.lang.NoSuchFieldError: TextAppearance_textAllCaps   at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:93)   at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:40)   at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:68)   at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)   at com.android.layoutlib.bridge.bars.CustomBar.<init>(CustomBar.java:95)   at com.android.layoutlib.bridge.bars.StatusBar.<init>(StatusBar.java:67)   at com.android.layoutlib.bridge.impl.Layout.createStatusBar(Layout.java:224)   at com.android.layoutlib.bridge.impl.Layout.<init>(Layout.java:146) Copy stack to clipboard
