### ISSUE TITLE
java.lang.IllegalArgumentException: path must be convex

### ISSUE THREAD

**Issue by onuryurtturk** [florent37/DiagonalLayout#11]
When I change height of diagonalLayout on xml, app is crashing. Just I can set 250dp.
Any solution?

**Comment by florent37** [comment]
have you try on the new version ?

**Comment by mradzinski** [comment]
@florent37, I've tried it. It seems (and it's pretty obvious) that if your view is too small for the angle of the diagonal path to be convex then this error gets thrown. I wouldn't mind that much considering that if the user wants the layout to be of 50dp then he/she will have to reduce the angle accordingly.

In other words: You CAN'T have a rectangle of 5cm (h) x 50cm (w) and expect to trace a diagonal of 75 degrees from top right corner to bottom left corner.

![untitled diagram](https://cloud.githubusercontent.com/assets/4214209/24877121/8ab08e94-1e04-11e7-977f-783554a71b85.png)

**Comment by onuryurtturk** [comment]
@florent37 yeap, I also tried it

**Comment by mradzinski** [comment]
@onuryurtturk I understand that, but this is not certainly an issue. This library's idea is to allow you to have a diagonal cut that goes from corner to corner. If you refer to the picture I uploaded in my previous answer you'll see why the exception is being thrown... that's pretty much what you are trying to achieve and that's not the main purpose of this library.

**Comment by florent37** [comment]
try with . 1.0.9

compile 'com.github.florent37:diagonallayout:1.0.9'
