### ISSUE TITLE
Bug: shadow looks weird

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [florent37/DiagonalLayout#2]
I took a screenshot and zoomed in because I didn't know if it's just my eyes :
Original:
![device-2016-10-23-222945](https://cloud.githubusercontent.com/assets/5357526/19628879/b88fbcb8-9970-11e6-9499-824e4e554d42.png)

After zooming in:
![maxthonsnap20161023223522](https://cloud.githubusercontent.com/assets/5357526/19628894/0c7cc9ec-9971-11e6-83d4-b2d9bbd627cc.png)

**Comment by AndroidDeveloperLB** [comment]
Also, btw, is this the entire sample? Where are those that are on the main page?

**Comment by florent37** [comment]
the shadow came from android:elevation.
this elevation only works with shapes, so I added a view with a rect shape behind the lauout, and totated it. I think it's cropped because of a clipping

**Comment by florent37** [comment]
try to change the layout from the setContentView(R.layout) to have the others samples

**Comment by AndroidDeveloperLB** [comment]
Is it possible to avoid the clipping?
Also, can you update the sample to show the other demos?
From what I see, "activity_main" looks the nicest :)

**Comment by florent37** [comment]
it should be fixed in the 1.0.3 👍

**Comment by AndroidDeveloperLB** [comment]
Thank you !
