### ISSUE TITLE
Multiple sided diagonal cuts

### ISSUE THREAD

**Issue by RahulSDeshpande** [florent37/DiagonalLayout#23]
Hey @florent37 !!
Great lib, an old fan of your work since many years !!

This issue is regarding a concern, that **is it possible to cut the layout multiple sides**.
Like if **I want to cut the layout from left & right at the same time with their respective angles**.

Thanks man 👍

**Comment by JAICHANGPARK** [comment]
I had same problem 
version 1.0.8

**Comment by KieuQ** [comment]
you can combine two DiagonalLayouts to achieve multisided diagonal
e.g., the first DiagonalLayout's height has the full intended length then the second DiagonalLayout overlaps the first one and only goes half the length of the intended length.
heres an [example](https://github.com/KieuQ/diagonal-layout-frame)

**Comment by florent37** [comment]
yes, combine with 2 diagonal layouts !
