### ISSUE TITLE
Not working on Android 4.1.1

### ISSUE THREAD

**Issue by passiondroid** [florent37/DiagonalLayout#8]
I created two genymotion emulators for testing with Android 6.0 and 4.1.1
DiagonalLayout was working fine on android 6.0 but was showing a straight line on 4.1.1
Please check the screenshot below - 

![screen shot 2016-12-04 at 3 07 02 pm](https://cloud.githubusercontent.com/assets/1834030/20865287/edec5838-ba33-11e6-820c-c63d584fa144.png)

This library is very helpful but needs backward compatible to atleast sdk version 15

**Comment by mradzinski** [comment]
@passiondroid, I checked the library code and there's no apparent reason for it not to work on 4.1.1. I'm attaching a screenshot of an app I'm developing that makes use of this library and which is running on a Genymotion Samsung Galaxy 3 emulator (4.1.1 too). Try taking away the elevation, that might be the reason why you are having rendering problems.

<img width="447" alt="captura de pantalla 2017-02-23 a las 01 02 18" src="https://cloud.githubusercontent.com/assets/4214209/23244430/e3434b34-f963-11e6-8078-339be99f153b.png">
